export const initialFormState = {
  sourceAccountId: '',
  destinationAccountId: '',
  amount: '',
  currency: 'INR',
  referenceNumber: '',
  reference: '',
  remarks: '',
  recipientName: '',
  accountHolder: '',
  accountNumber: '',
  confirmAccountNumber: '',
  ifscCode: '',
  ifsc: '',
  bankName: '',
  transferType: 'Normal',
  transferMethod: 'Bank Transfer'
};

export const translations = {
  en: {
    appName: 'SmartPay',
    dashboard: 'Dashboard',
    payments: 'Payments',
    transactions: 'Transactions',
    beneficiaries: 'Beneficiaries',
    inviteTitle: 'Invite & Earn',
    inviteText: 'Invite your friends and earn exciting rewards',
    inviteButton: 'Invite Now',
    needHelp: 'Need Help?',
    support: '24/7 Support',
    searchPlaceholder: 'Search by name, payment ID, account...',
    greeting: 'Good Morning, Soumitha!',
    greetingSub: "Here's what's happening with your account today.",
    quickActions: 'Quick Actions',
    customize: 'Customize',
    account: 'Account',
    makePayment: 'Make Payment',
    checkBalance: 'Check Balance',
    schedulePayment: 'Schedule Payment',
    groupSplit: 'Group Split',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    loadingPayments: 'Loading payments...',
    noPayments: 'No payments found.',
    spendingOverview: 'Spending Overview',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    totalSpent: 'Total Spent',
    insight: 'You can compare month-wise spending using the selector above.',
    upcomingPayments: 'Upcoming Payments',
    noScheduled: 'No scheduled payments yet.',
    sendMoney: 'Send money instantly',
    sendMoneySub: 'Anytime, anywhere with SmartPay',
    payNow: 'Make a Payment',
    makePaymentTitle: 'Make Payment',
    schedulePaymentTitle: 'Schedule Payment',
    selectMethodSub: 'Choose a payment method to continue. You can switch between Bank Transfer and UPI.',
    bankTransfer: 'Bank Transfer',
    bankTransferSub: 'Transfer money between accounts',
    upi: 'UPI',
    upiSub: 'Pay instantly using UPI ID',
    sourceAccount: 'Source Account ID',
    destinationAccount: 'Destination Account ID',
    amount: 'Amount',
    currency: 'Currency',
    reference: 'Reference Number',
    remarks: 'Remarks',
    upiId: 'UPI ID',
    payingAmount: 'Paying Amount',
    mode: 'Mode',
    reset: 'Cancel',
    processing: 'Submitting...',
    submitPayment: 'Create Payment',
    submitSchedule: 'Schedule',
    close: 'Close',
    totalAmount: 'Total Amount',
    numberOfPeople: 'Number of People',
    perPerson: 'Per person',
    paymentCreated: 'Payment created.',
    paymentScheduled: 'Payment scheduled.',
    accountComing: 'Account details panel coming next.',
    totalTracked: 'Total payments tracked:'
  },
  hi: {
    appName: 'स्मार्टपे',
    dashboard: 'डैशबोर्ड',
    payments: 'भुगतान',
    transactions: 'लेन-देन',
    beneficiaries: 'लाभार्थी',
    inviteTitle: 'आमंत्रित करें और कमाएँ',
    inviteText: 'अपने दोस्तों को आमंत्रित करें और शानदार रिवॉर्ड्स पाएँ',
    inviteButton: 'अभी आमंत्रित करें',
    needHelp: 'सहायता चाहिए?',
    support: '24/7 सहायता',
    searchPlaceholder: 'नाम, भुगतान आईडी, खाता से खोजें...',
    greeting: 'सुप्रभात, सुमीथा!',
    greetingSub: 'आज आपके खाते में क्या हो रहा है, यह देखें।',
    quickActions: 'त्वरित कार्य',
    customize: 'कस्टमाइज़',
    account: 'खाता',
    makePayment: 'भुगतान करें',
    checkBalance: 'बैलेंस देखें',
    schedulePayment: 'भुगतान शेड्यूल करें',
    groupSplit: 'समूह विभाजन',
    recentTransactions: 'हाल के लेन-देन',
    viewAll: 'सभी देखें',
    loadingPayments: 'भुगतान लोड हो रहे हैं...',
    noPayments: 'कोई भुगतान नहीं मिला।',
    spendingOverview: 'खर्च का अवलोकन',
    thisMonth: 'इस महीने',
    lastMonth: 'पिछला महीना',
    totalSpent: 'कुल खर्च',
    insight: 'ऊपर दिए गए चयन से महीनेवार खर्च की तुलना कर सकते हैं।',
    upcomingPayments: 'आगामी भुगतान',
    noScheduled: 'अभी कोई शेड्यूल भुगतान नहीं है।',
    sendMoney: 'तुरंत पैसा भेजें',
    sendMoneySub: 'कभी भी, कहीं भी SmartPay के साथ',
    payNow: 'भुगतान करें',
    makePaymentTitle: 'भुगतान करें',
    schedulePaymentTitle: 'भुगतान शेड्यूल करें',
    selectMethodSub: 'आगे बढ़ने के लिए भुगतान विधि चुनें। आप बैंक ट्रांसफर और UPI के बीच स्विच कर सकते हैं।',
    bankTransfer: 'बैंक ट्रांसफर',
    bankTransferSub: 'खाते से खाते में ट्रांसफर करें',
    upi: 'UPI',
    upiSub: 'UPI ID से तुरंत भुगतान करें',
    sourceAccount: 'स्रोत खाता आईडी',
    destinationAccount: 'गंतव्य खाता आईडी',
    amount: 'राशि',
    currency: 'मुद्रा',
    reference: 'संदर्भ संख्या',
    remarks: 'टिप्पणी',
    upiId: 'UPI ID',
    payingAmount: 'देय राशि',
    mode: 'विधि',
    reset: 'रद्द करें',
    processing: 'सबमिट हो रहा है...',
    submitPayment: 'भुगतान बनाएं',
    submitSchedule: 'शेड्यूल करें',
    close: 'बंद करें',
    totalAmount: 'कुल राशि',
    numberOfPeople: 'लोगों की संख्या',
    perPerson: 'प्रति व्यक्ति',
    paymentCreated: 'भुगतान बनाया गया।',
    paymentScheduled: 'भुगतान शेड्यूल किया गया।',
    accountComing: 'खाता विवरण पैनल जल्द आएगा।',
    totalTracked: 'कुल ट्रैक किए गए भुगतान:'
  },
  ta: {
    appName: 'ஸ்மார்ட்பே',
    dashboard: 'டாஷ்போர்டு',
    payments: 'பணம் செலுத்தல்',
    transactions: 'பரிவர்த்தனைகள்',
    beneficiaries: 'பயனாளிகள்',
    inviteTitle: 'அழைக்கவும் & சம்பாதிக்கவும்',
    inviteText: 'உங்கள் நண்பர்களை அழைத்து சிறந்த பரிசுகளை பெறுங்கள்',
    inviteButton: 'இப்போது அழைக்கவும்',
    needHelp: 'உதவி தேவையா?',
    support: '24/7 ஆதரவு',
    searchPlaceholder: 'பெயர், payment ID, account மூலம் தேடவும்...',
    greeting: 'காலை வணக்கம், சுமிதா!',
    greetingSub: 'இன்று உங்கள் கணக்கில் என்ன நடக்கிறது என்பதைப் பார்க்கவும்.',
    quickActions: 'விரைவு செயல்கள்',
    customize: 'தனிப்பயன்',
    account: 'கணக்கு',
    makePayment: 'பணம் செலுத்து',
    checkBalance: 'இருப்பு பார்க்க',
    schedulePayment: 'செலுத்தலை திட்டமிடு',
    groupSplit: 'குழு பிரிப்பு',
    recentTransactions: 'சமீபத்திய பரிவர்த்தனைகள்',
    viewAll: 'அனைத்தையும் காண்க',
    loadingPayments: 'பணம் செலுத்தல்கள் ஏற்றப்படுகிறது...',
    noPayments: 'பணம் செலுத்தல் எதுவும் இல்லை.',
    spendingOverview: 'செலவு கண்ணோட்டம்',
    thisMonth: 'இந்த மாதம்',
    lastMonth: 'கடந்த மாதம்',
    totalSpent: 'மொத்த செலவு',
    insight: 'மேலே உள்ள தேர்வின் மூலம் மாதாந்திர செலவுகளை ஒப்பிடலாம்.',
    upcomingPayments: 'வரவிருக்கும் பணம் செலுத்தல்கள்',
    noScheduled: 'இதுவரை திட்டமிடப்பட்ட பணம் செலுத்தல் இல்லை.',
    sendMoney: 'உடனே பணம் அனுப்பவும்',
    sendMoneySub: 'எப்போது வேண்டுமானாலும், எங்கே இருந்தாலும் SmartPay உடன்',
    payNow: 'பணம் செலுத்து',
    makePaymentTitle: 'பணம் செலுத்து',
    schedulePaymentTitle: 'செலுத்தலை திட்டமிடு',
    selectMethodSub: 'தொடர ஒரு பணம் செலுத்தும் முறையை தேர்ந்தெடுக்கவும். நீங்கள் Bank Transfer மற்றும் UPI இடையே மாறலாம்.',
    bankTransfer: 'வங்கி பரிமாற்றம்',
    bankTransferSub: 'கணக்கு-to-கணக்கு பரிமாற்றம்',
    upi: 'UPI',
    upiSub: 'UPI ID மூலம் உடனடி செலுத்தல்',
    sourceAccount: 'மூல கணக்கு ஐடி',
    destinationAccount: 'இலக்கு கணக்கு ஐடி',
    amount: 'தொகை',
    currency: 'நாணயம்',
    reference: 'குறிப்பு எண்',
    remarks: 'குறிப்பு',
    upiId: 'UPI ID',
    payingAmount: 'செலுத்தும் தொகை',
    mode: 'முறை',
    reset: 'ரத்து செய்',
    processing: 'சமர்ப்பிக்கப்படுகிறது...',
    submitPayment: 'பணம் செலுத்து',
    submitSchedule: 'திட்டமிடு',
    close: 'மூடு',
    totalAmount: 'மொத்த தொகை',
    numberOfPeople: 'நபர்களின் எண்ணிக்கை',
    perPerson: 'ஒரு நபருக்கு',
    paymentCreated: 'பணம் செலுத்தல் உருவாக்கப்பட்டது.',
    paymentScheduled: 'பணம் செலுத்தல் திட்டமிடப்பட்டது.',
    accountComing: 'கணக்கு விவரங்கள் விரைவில் வரும்.',
    totalTracked: 'மொத்தமாக கண்காணிக்கப்பட்ட பணம் செலுத்தல்கள்:'
  },
  te: {
    appName: 'స్మార్ట్‌పే',
    dashboard: 'డాష్‌బోర్డ్',
    payments: 'చెల్లింపులు',
    transactions: 'లావాదేవీలు',
    beneficiaries: 'లబ్ధిదారులు',
    inviteTitle: 'ఆహ్వానించండి & సంపాదించండి',
    inviteText: 'మీ స్నేహితులను ఆహ్వానించి అద్భుతమైన రివార్డ్స్ పొందండి',
    inviteButton: 'ఇప్పుడు ఆహ్వానించండి',
    needHelp: 'సహాయం కావాలా?',
    support: '24/7 సపోర్ట్',
    searchPlaceholder: 'పేరు, payment ID, account ద్వారా వెతకండి...',
    greeting: 'శుభోదయం, సుమితా!',
    greetingSub: 'ఈ రోజు మీ ఖాతాలో ఏమి జరుగుతోందో చూడండి.',
    quickActions: 'త్వరిత చర్యలు',
    customize: 'కస్టమైజ్',
    account: 'ఖాతా',
    makePayment: 'చెల్లింపు చేయండి',
    checkBalance: 'బ్యాలెన్స్ చూడండి',
    schedulePayment: 'చెల్లింపు షెడ్యూల్ చేయండి',
    groupSplit: 'గ్రూప్ స్ప్లిట్',
    recentTransactions: 'ఇటీవలి లావాదేవీలు',
    viewAll: 'అన్ని చూడండి',
    loadingPayments: 'చెల్లింపులు లోడ్ అవుతున్నాయి...',
    noPayments: 'చెల్లింపులు కనబడలేదు.',
    spendingOverview: 'ఖర్చుల అవలోకనం',
    thisMonth: 'ఈ నెల',
    lastMonth: 'గత నెల',
    totalSpent: 'మొత్తం ఖర్చు',
    insight: 'పైన ఉన్న ఎంపికతో నెలవారీ ఖర్చులను పోల్చవచ్చు.',
    upcomingPayments: 'రాబోయే చెల్లింపులు',
    noScheduled: 'ఇంకా షెడ్యూల్ చేసిన చెల్లింపులు లేవు.',
    sendMoney: 'తక్షణమే డబ్బు పంపండి',
    sendMoneySub: 'ఎప్పుడైనా, ఎక్కడైనా SmartPay తో',
    payNow: 'చెల్లింపు చేయండి',
    makePaymentTitle: 'చెల్లింపు చేయండి',
    schedulePaymentTitle: 'చెల్లింపు షెడ్యూల్ చేయండి',
    selectMethodSub: 'కొనసాగించడానికి చెల్లింపు విధానాన్ని ఎంచుకోండి. మీరు Bank Transfer మరియు UPI మధ్య మారవచ్చు.',
    bankTransfer: 'బ్యాంక్ ట్రాన్స్‌ఫర్',
    bankTransferSub: 'ఖాతా నుండి ఖాతాకు ట్రాన్స్‌ఫర్',
    upi: 'UPI',
    upiSub: 'UPI ID ద్వారా తక్షణ చెల్లింపు',
    sourceAccount: 'మూల ఖాతా ఐడి',
    destinationAccount: 'గమ్య ఖాతా ఐడి',
    amount: 'మొత్తం',
    currency: 'కరెన్సీ',
    reference: 'రిఫరెన్స్ నంబర్',
    remarks: 'గమనికలు',
    upiId: 'UPI ID',
    payingAmount: 'చెల్లించాల్సిన మొత్తం',
    mode: 'మోడ్',
    reset: 'రద్దు చేయండి',
    processing: 'సమర్పిస్తోంది...',
    submitPayment: 'చెల్లింపు చేయండి',
    submitSchedule: 'షెడ్యూల్ చేయండి',
    close: 'మూసివేయండి',
    totalAmount: 'మొత్తం మొత్తం',
    numberOfPeople: 'వ్యక్తుల సంఖ్య',
    perPerson: 'ప్రతి వ్యక్తికి',
    paymentCreated: 'చెల్లింపు సృష్టించబడింది.',
    paymentScheduled: 'చెల్లింపు షెడ్యూల్ చేయబడింది.',
    accountComing: 'ఖాతా వివరాల ప్యానెల్ త్వరలో వస్తుంది.',
    totalTracked: 'మొత్తం ట్రాక్ చేసిన చెల్లింపులు:'
  }
};

export const languageOptions = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' }
];
